"use client";
import { useState } from "react";
import { ArrowRight, Construction, Database, Filter, Plus, Search, ShieldCheck, Sparkles } from "lucide-react";
import { useAppStore } from "@/stores/app-store";

type Config = { title:string; eyebrow:string; description:string; action:string; stats:[string,string,string][]; items:string[] };
const configs:Record<string,Config>={
  assistant:{title:"Ask ReleaseLens",eyebrow:"RELEASE-AWARE AI",description:"Ask grounded questions using evidence from the selected release.",action:"New conversation",stats:[["Grounded answers","96.8%","Healthy"],["Avg. response","2.4s","-12%"],["Citations verified","98.7%","Passing"]],items:["What changed in this release?","Which APIs have breaking changes?","Trace checkout to code and tests"]},
  releases:{title:"Release management",eyebrow:"IMMUTABLE SNAPSHOTS",description:"Create, validate, compare and publish trusted release knowledge packages.",action:"Create release",stats:[["Published","24","+3 this month"],["Awaiting validation","2","Action needed"],["Snapshot integrity","100%","Signed"]],items:["v3.2.1 Â· Published Â· BLD-8492","v3.2.0 Â· Published Â· BLD-8311","v3.1.8 Â· Superseded Â· BLD-8024"]},
  "data-sources":{title:"Data sources",eyebrow:"ENTERPRISE CONNECTORS",description:"Manage repositories, project planning, and knowledge documents.",action:"Connect source",stats:[["Connected","24","10 categories"],["Healthy","23","95.8%"],["Artifacts","48.2K","+1.2K today"]],items:["GitHub Â· Healthy","Project Management Tool Â· Healthy","Knowledge Base Â· Sync delayed"]},
  knowledge:{title:"Knowledge explorer",eyebrow:"RELEASE-SCOPED SEARCH",description:"Search services, APIs, requirements, tests and architecture decisions.",action:"Advanced search",stats:[["Entities","18.4K","Indexed"],["Relationships","62.8K","Graph ready"],["Avg. confidence","94.2%","High"]],items:["PaymentService Â· Service","POST /checkout Â· API","ADR-042 Event-driven payments Â· Decision"]},
  traceability:{title:"Traceability explorer",eyebrow:"END-TO-END LINEAGE",description:"Follow requirements through code, tests, builds, deployments and releases.",action:"Explore graph",stats:[["Coverage","92.4%","+4.2%"],["Missing links","38","Review"],["Paths indexed","12.8K","Ready"]],items:["Requirement â†’ Feature â†’ Pull request","Component â†’ API â†’ Integration test","Build â†’ Deployment â†’ Release"]},
  "impact-analysis":{title:"Impact analysis",eyebrow:"WHAT-IF INTELLIGENCE",description:"Analyze direct and indirect effects before making a product change.",action:"Run analysis",stats:[["Services at risk","4","Medium"],["Affected tests","18","Review"],["Risk score","62/100","Moderate"]],items:["CheckoutService Â· Direct impact","Payment API Â· Contract review","Regression suite Â· 18 tests"]},
  "api-explorer":{title:"API explorer",eyebrow:"CONTRACT INTELLIGENCE",description:"Explore endpoints, schemas, authentication and release-level changes.",action:"Compare APIs",stats:[["Endpoints","284","12 services"],["Changed","18","This release"],["Breaking","2","Action needed"]],items:["POST /v2/checkout Â· Modified","GET /v2/orders/{id} Â· Stable","DELETE /v1/cart Â· Deprecated"]},
  "database-explorer":{title:"Database explorer",eyebrow:"SCHEMA INTELLIGENCE",description:"Inspect schemas, relationships, migrations and release history.",action:"Compare schema",stats:[["Tables","126","8 schemas"],["Migrations","14","This release"],["Breaking","1","Review"]],items:["orders Â· 18 columns","payment_transactions Â· Modified","V042__add_checkout_state.sql Â· Applied"]},
  "test-intelligence":{title:"Test intelligence",eyebrow:"QUALITY & COVERAGE",description:"Understand test outcomes, coverage gaps and regression risk.",action:"View test run",stats:[["Passed","12,482","98.4%"],["Failed","38","-12 today"],["Coverage","87.6%","+2.1%"]],items:["CheckoutIntegrationTest Â· Passed","PaymentRetryTest Â· Flaky","RefundContractTest Â· Failed"]},
  reports:{title:"Reports",eyebrow:"RELEASE INSIGHTS",description:"Generate readiness, change, quality, cost and compliance reports.",action:"Generate report",stats:[["Generated","42","This month"],["Scheduled","8","Active"],["Templates","10","Available"]],items:["Release Readiness Report","Breaking Change Report","Traceability Coverage Report"]},
  governance:{title:"Governance",eyebrow:"DATA TRUST & CONTROL",description:"Manage cataloging, lineage, access control, quality and retention.",action:"Review policies",stats:[["Quality score","96.1%","Healthy"],["Policy checks","18.2K","Passing"],["Open issues","14","Review"]],items:["Data catalog Â· Current","Access-control mappings Â· 2 warnings","Retention policies Â· Compliant"]},
  guardrails:{title:"AI guardrails",eyebrow:"SAFE & GROUNDED AI",description:"Monitor release isolation, citations, injection attempts and tool permissions.",action:"Configure policies",stats:[["Validated","8,492","This week"],["Blocked","12","Protected"],["Pass rate","99.8%","Healthy"]],items:["Cross-release evidence blocked","Prompt injection detected","Unauthorized tool call prevented"]},
  admin:{title:"Administration",eyebrow:"PLATFORM CONTROL",description:"Manage users, roles, models, prompts and evaluation programs.",action:"Add user",stats:[["Active users","284","12 teams"],["Roles","8","RBAC + ABAC"],["Models","4","All healthy"]],items:["Alex Morgan Â· Platform Architect","Maya Chen Â· Release Manager","James Park Â· Engineering Lead"]},
  settings:{title:"Settings",eyebrow:"WORKSPACE CONFIGURATION",description:"Configure products, environments, notifications, appearance and security.",action:"Save changes",stats:[["Products","6","Configured"],["Environments","3","Active"],["Integrations","12","Connected"]],items:["General & product settings","Appearance & notifications","API keys & security"]}
};

export function WorkspacePage({section}:{section:string}){
  const config=configs[section]??{title:"Workspace",eyebrow:"RELEASELENS",description:"This workspace is ready for configuration.",action:"Get started",stats:[["Status","Ready","Available"],["Release","Current","Selected"],["Access","Granted","Authorized"]],items:["Workspace overview","Release context","Platform activity"]};
  const release=useAppStore(s=>s.selectedRelease);const [query,setQuery]=useState("");
  const projectManagementUrl=process.env.NEXT_PUBLIC_PROJECT_MANAGEMENT_URL||"http://127.0.0.1:8000";
  return <main className="dashboard workspace-page"><div className="page-heading"><div><span className="eyebrow">{config.eyebrow}</span><h1>{config.title}</h1><p>{config.description} Release context: <b>{release}</b>.</p></div><button><Plus/> {config.action}</button></div><section className="workspace-stats">{config.stats.map(([label,value,note],i)=><article className="card" key={label}><span>{i===0?<Database/>:i===1?<ShieldCheck/>:<Sparkles/>}</span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>)}</section><section className="card workspace-content"><div className="workspace-toolbar"><label><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Search ${config.title.toLowerCase()}â€¦`} aria-label={`Search ${config.title}`}/></label><button><Filter/> Filters</button></div><div className="workspace-list">{config.items.filter(x=>x.toLowerCase().includes(query.toLowerCase())).map((item,i)=>{const isProjectManagement=section==="data-sources"&&item.startsWith("Project Management Tool");return <button key={item} onClick={()=>{if(isProjectManagement)window.open(projectManagementUrl,"_blank","noopener,noreferrer")}} aria-label={isProjectManagement?"Open Project Management Tool":undefined}><span>{i+1}</span><div><strong>{item.split(" Â· ")[0]}</strong><small>{item.split(" Â· ").slice(1).join(" Â· ")||`Release ${release}`}</small></div><ArrowRight/></button>})}</div><div className="phase-note"><Construction/><div><strong>Functional area initialized</strong><p>This route now preserves navigation and global release context. Its specialized workflows will be expanded in the next product phase.</p></div></div></section></main>;
}
